when@dev:
#    _errors:
#        resource: '@FrameworkBundle/Resources/config/routing/errors.php'
#        prefix: /_error
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error
